services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: agenda
      POSTGRES_PASSWORD: agenda
      POSTGRES_DB: agenda_gift
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: